### ISSUE TITLE
Unable to search /System/Volumes/Data ?

### ISSUE THREAD

**Issue by luckman212** [sveinbjornt/searchfs#8]
Catalina 10.15.3

`searchfs` seems unable to search the r/w mountpoint where all user data is stored. Tried v0.3 from https://sveinbjorn.org/files/software/searchfs.zip as well as compiling from `master` - same result:
```sh
$ ./searchfs -l
/dev/disk1s5 (apfs): /
/dev/disk1s1 (apfs): /System/Volumes/Data
/dev/disk1s4 (apfs): /private/var/vm
/dev/disk2s2 (hfs ): /Volumes/TimeMachine

$ ./searchfs -v / USBDriverKit.framework$
/System/DriverKit/System/Library/Frameworks/USBDriverKit.framework
/System/Library/Frameworks/USBDriverKit.framework

$ ./searchfs -v /System/Volumes/Data foo
Not a volume mount point: /System/Volumes/Data

$ ./searchfs -v /dev/disk1s1 foo
Not a volume mount point: /System/Volumes/Data
```

Not sure if it matters, but I also tried granting the binary Full Disk Access, which did not make any difference. Am I doing something wrong?

**Comment by sveinbjornt** [comment]
I'm still running on Mojave so I'm not sure about how Catalina may have broken things. Will take a look at this issue as soon as I upgrade.

**Comment by decodism** [comment]
Same issue on Big Sur 11.1

**Comment by jevinskie** [comment]
Manually allow-listing /System/Volumes/Data in is_mount_path() seems to do the trick.

**Comment by checktext00** [comment]
> Manually allow-listing /System/Volumes/Data in is_mount_path() seems to do the trick.

@jevinskie how do I do that?


I'm also unable to search my Data volume
```
% searchfs -l
/dev/disk1s5s1 (apfs): /
/dev/disk1s4 (apfs): /System/Volumes/VM
/dev/disk1s2 (apfs): /System/Volumes/Preboot
/dev/disk1s6 (apfs): /System/Volumes/Update
/dev/disk1s1 (apfs): /System/Volumes/Data
```

when trying to search for all files on the root filesystem these are the only results:
```
% searchfs -f *         
/System/Library/Assistant/SyncConfiguration/com.apple.siri.applications.plist
/System/Library/Automator/Hide All Applications.action/Contents/MacOS/Hide All Applications
/System/Library/Automator/Quit All Applications.action/Contents/MacOS/Quit All Applications
/System/Library/CoreServices/Automator Application Stub.app/Contents/Resources/ApplicationStub.icns
/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/ApplicationsFolderIcon.icns
/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/ServerApplicationsFolderIcon.icns
/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarApplicationsFolder.icns
/System/Library/Frameworks/AppleScriptKit.framework/Versions/A/Resources/ASKApplicationSuite.eventHandlers
/System/Library/Frameworks/AppleScriptKit.framework/Versions/A/Resources/ASKApplicationSuite.scriptSuite
/System/Library/Frameworks/AppleScriptKit.framework/Versions/A/Resources/ASKApplicationSuite.scriptTerminology
/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Resources/BridgeSupport/ApplicationServices.arm64e.bridgesupport
/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Resources/BridgeSupport/ApplicationServices.bridgesupport
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/Resources/ListConfigurations/com.apple.LSSharedFileList.DockApplications.plist
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/Resources/ListConfigurations/com.apple.LSSharedFileList.RecentApplications.plist
/System/Library/PrivateFrameworks/JavaScriptAppleEvents.framework/Versions/A/Resources/BridgeSupportCache/ApplicationServices.plist
/System/Library/PrivateFrameworks/StorageManagement.framework/PlugIns/ApplicationsStorageExtension.appex/Contents/MacOS/ApplicationsStorageExtension
/System/Library/SystemProfiler/SPApplicationsReporter.spreporter/Contents/MacOS/SPApplicationsReporter
/System/Library/SystemProfiler/SPDisabledApplicationsReporter.spreporter/Contents/MacOS/SPDisabledApplicationsReporter
/System/Library/Templates/Data/Library/Apple/Library/Bundles/TCC_Compatibility.bundle/Contents/Resources/AllowApplicationsList.plist
/usr/share/zsh/5.8/functions/_mac_applications
```

and
```
% searchfs -v /System/Volumes/Data * 
Not a volume mount point: /System/Volumes/Data
```

test.py
```
% python ./test.py 
Running tests... (this may take a while)
./searchfs --list
./searchfs -v '/dev/disk1s5s1' 's' -m 10
./searchfs --volume '/' 'C' --limit 10
./searchfs ^README -s -m 20
./searchfs .plist$ --limit 25
./searchfs -d 's' -m 15
./searchfs -d -e Contents -s -m 10
./searchfs -n 'Hold the newsreaders nose squarely, waiter, or friendly milk will countermand my trousers' -m 200
./searchfs -f 's' -m 7
./searchfs -e 'ls'
./searchfs -pse Contents
./searchfs -xse Frameworks
Traceback (most recent call last):
  File "./test.py", line 100, in <module>
    run_tests()
  File "./test.py", line 85, in run_tests
    assert len(lines) > 10
AssertionError
```

system: macOS 11
compiled from source

**Comment by sveinbjornt** [comment]
This has been resolved in the latest release: https://github.com/sveinbjornt/searchfs/releases/tag/0.4.0

**Comment by checktext00** [comment]
> This has been resolved in the latest release: https://github.com/sveinbjornt/searchfs/releases/tag/0.4.0

thank you, I will let know how it goes

**Comment by checktext00** [comment]
It seems to mostly work, thanks again. There is now another issue with the python test though
```
% cd ~/searchfs
% python3 test.py
Running tests... (this may take a while)
./searchfs --list
./searchfs -v /dev/disk1s5s1 s -m 10
./searchfs --volume / C --limit 10
./searchfs -v / ^README -s -m 20
./searchfs -v / .plist$ --limit 25
./searchfs -v / -d s -m 15
./searchfs -v / -d -e Contents -s -m 10
./searchfs -v / -f s -m 7
./searchfs -v / -e ls
./searchfs -v / -pse Contents
./searchfs -v / -se Frameworks
./searchfs 
Testing for no matches...
./searchfs -v / XYZXYZXYZ
Testing mutually exclusive -d and -f flags...
./searchfs -d -f some_term
Testing search string longer than PATH_MAX...
./searchfs aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Testing prefix match without exact-match...
./searchfs -v / ^README -m 100
Testing suffix match without exact-match...
./searchfs -v / .plist$ -m 100
Testing case-sensitive prefix match...
./searchfs -v / -s ^readme -m 100
Traceback (most recent call last):
  File "test.py", line 167, in <module>
    run_tests()
  File "test.py", line 138, in run_tests
    assert len(lines) == 0, \
AssertionError: Expected no matches for case-sensitive 'readme' prefix, but got 1 results
```

searchfs 4.0 compiled from source, commit 065a21c, macOS 11

**Comment by sveinbjornt** [comment]
Yeah, that particular test is a bit dodgy and I should probably remove it, makes assumptions about the environment it's running in (GitHub Actions CI).
